name: Rust CI

on:
  push:
    paths:
      - 'templates/rust/**'
      - '.github/workflows/rust**'
  pull_request:
    paths:
      - 'templates/rust/**'
      - '.github/workflows/rust**'


  # schedule:
  #   # weekly build every FRI
  #   - cron: "0 6 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: templates/rust
        run: cargo build --verbose
      - name: Run tests
        working-directory: templates/rust
        run: cargo test test_should_not_fail --verbose
